#unstable_features            = true
#
#control_brace_style          = "AlwaysSameLine"
#combine_control_expr         = false
#condense_wildcard_suffixes   = true
#brace_style                  = "AlwaysNextLine"
#empty_item_single_line       = true
#format_strings               = true
#format_macro_matchers        = true
#imports_layout               = "HorizontalVertical"
#merge_imports                = true
#match_block_trailing_comma   = true
max_width                    = 80
#force_multiline_blocks       = true
newline_style                = "Unix"
#normalize_comments           = true
#reorder_impl_items           = true
#struct_field_align_threshold = 1
#struct_lit_single_line       = false
#trailing_comma               = "Never"
#wrap_comments                = true
#blank_lines_upper_bound      = 2
